# -*- coding: utf-8 -*-
"""GITHUB PRO09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMYHOSVbhLrzGq3MVhzvgLonr5T4C-RO
"""

# Commented out IPython magic to ensure Python compatibility.
# %%markdown
# #**GitHub Project**
# **Umaima Uzair Khan**

# # Week 9 Git and GitHub Project
# ## Simple Calculator
# This notebook contains a beginner-level calculator project.
# The project will be uploaded to GitHub using Git.

print("===== SIMPLE CALCULATOR =====")
number1 = float(input("Enter first number: "))
number2 = float(input("Enter second number: "))
print("Choose an operation: +, -, *, /")
operation = input("Enter operation: ")

if operation == "+":
    print("Answer:", number1 + number2)
elif operation == "-":
    print("Answer:", number1 - number2)
elif operation == "*":
    print("Answer:", number1 * number2)
elif operation == "/":
    if number2 == 0:
        print("Division by zero is not possible.")
    else:
        print("Answer:", number1 / number2)
else:
    print("Invalid operation.")

# --- Bonus: Isi cell se README.md aur .gitignore bhi bana deta hun taake aapko alag cell na banana pare ---

# README.md banana
with open("README.md", "w") as f:
    f.write("""# Simple Calculator
## Project Description
This is a beginner-level calculator created in Python using Jupyter Notebook.
## Features
- Addition
- Subtraction
- Multiplication
- Division
- Division-by-zero checking
## Python Concepts Used
- input(), print(), float(), if-elif-else
## How to Run
1. Open notebook in Jupyter
2. Run the cell
## Author
Student Name: Abdul Majid Memon
""")
print("\nREADME.md created!")

# .gitignore banana
with open(".gitignore", "w") as f:
    f.write(""".ipynb_checkpoints/
__pycache__/
*.pyc
""")
print(".gitignore created!")